### ISSUE TITLE
TypeError: expected string or bytes-like object, got 'NoneType'

### ISSUE THREAD

**Issue by mrsaffari** [diogo-alves/eml_attachments_extractor#5]
Traceback (most recent call last):
  File "D:\sales\eml-extractor-main\eml_extractor.py", line 113, in <module>
    main()
  File "D:\sales\eml-extractor-main\eml_extractor.py", line 108, in main
    extract_attachments(file, destination=args.destination)
  File "D:\sales\eml-extractor-main\eml_extractor.py", line 13, in extract_attachments
    basepath = destination / sanitize_foldername(email_subject)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sales\eml-extractor-main\eml_extractor.py", line 33, in sanitize_foldername
    return re.sub(illegal_chars, '_', name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by dlQue** [comment]
same issue
